apiVersion: v1
kind: Secret
metadata:
  name: ams-secrets
  namespace: ams
type: Opaque
stringData:
  DB_DSN: host=postgresql.default.svc.cluster.local port=5432 user=ams password=change-me dbname=ams sslmode=require TimeZone=Asia/Ho_Chi_Minh
  JWT_SECRET: change-this-jwt-secret
  REDIS_PASSWORD: change-this-redis-secret
